"use client";

import { Check, FileText, Layers3, Send, Star } from "lucide-react";
import { motion, useReducedMotion } from "framer-motion";

const steps = [
  { number: "01", title: "Collect", subtitle: "Open a door for kind words.", body: "Share a beautifully branded form or import praise that is already waiting across your channels.", icon: FileText, tone: "bg-[#f2f8ff] border-[#d8e7fa]", accent: "bg-[#0b61d9]" },
  { number: "02", title: "Curate", subtitle: "Keep the stories that carry weight.", body: "Review every response in one calm workspace, verify its source, and make the message feel complete.", icon: Layers3, tone: "bg-[#f0f9eb] border-[#d8e8cf]", accent: "bg-[#27885b]" },
  { number: "03", title: "Publish", subtitle: "Let proof do its work.", body: "Place a wall, carousel, or single quote wherever a future customer needs the confidence to act.", icon: Send, tone: "bg-[#fff8ee] border-[#eadfcf]", accent: "bg-[#c96d42]" },
];

function CollectVisual() { return <div className="w-full rounded-2xl border border-[#dce8f8] bg-white p-4 shadow-[0_12px_24px_rgba(19,72,145,.08)]"><div className="flex items-center gap-2"><span className="flex h-7 w-7 items-center justify-center rounded-lg bg-[#0b61d9] text-sm font-bold text-white">b</span><span className="text-[10px] font-bold text-[#173b71]">Tell us what changed</span></div><div className="mt-4 flex gap-1 text-[#f0a33a]">{[1,2,3,4,5].map((i) => <Star key={i} size={13} fill="currentColor" />)}</div><div className="mt-3 h-16 rounded-xl bg-[#f4f8fd] p-3"><span className="block h-1.5 w-full rounded bg-[#bed1e9]"/><span className="mt-2 block h-1.5 w-3/4 rounded bg-[#d9e5f2]"/></div><div className="mt-3 rounded-xl bg-[#0b61d9] py-2 text-center text-[10px] font-bold text-white">Send feedback</div></div>; }
function CurateVisual() { return <div className="w-full rounded-2xl border border-[#d8e8cf] bg-white p-4 shadow-[0_12px_24px_rgba(32,105,64,.08)]"><div className="flex items-center justify-between"><span className="text-[10px] font-bold text-[#173b71]">New response</span><span className="rounded-full bg-[#edf8e8] px-2 py-1 text-[8px] font-bold text-[#27885b]">VERIFIED</span></div><div className="mt-3 rounded-xl bg-[#f3f9ef] p-3"><div className="flex gap-0.5 text-[#eaa632]">{[1,2,3,4,5].map((i) => <Star key={i} size={10} fill="currentColor" />)}</div><p className="mt-2 text-[11px] font-semibold leading-relaxed text-[#294a3c]">“It feels like this was made for us.”</p></div><div className="mt-3 grid grid-cols-2 gap-2"><span className="rounded-lg bg-[#27885b] py-2 text-center text-[9px] font-bold text-white">Approve</span><span className="rounded-lg border border-[#d9e6d2] py-2 text-center text-[9px] font-bold text-[#587367]">Save for later</span></div></div>; }
function PublishVisual() { return <div className="w-full rounded-2xl border border-[#eadfcf] bg-white p-4 shadow-[0_12px_24px_rgba(120,73,32,.08)]"><div className="flex items-center gap-1.5"><i className="h-2 w-2 rounded-full bg-[#f3a18b]"/><i className="h-2 w-2 rounded-full bg-[#f0d175]"/><span className="ml-auto text-[8px] font-mono text-[#9194a1]">yourbrand.com</span></div><div className="mt-4 rounded-xl bg-[#fff4e8] p-3"><span className="flex items-center gap-1 text-[8px] font-bold text-[#c96d42]"><Check size={10}/> VERIFIED CUSTOMER</span><p className="mt-2 text-[11px] font-semibold leading-relaxed text-[#4f3c2e]">“The social proof finally feels like our brand.”</p><div className="mt-3 flex items-center gap-2 text-[9px] font-bold text-[#9a7d64]"><span className="h-5 w-5 rounded-full bg-[#b9d9e8]"/> Alex, founder</div></div></div>; }

const visuals = [CollectVisual, CurateVisual, PublishVisual];

export default function HowItWorksStacked({ titleAs: TitleTag = "h2" }: { titleAs?: "h1" | "h2" } = {}) {
  const reduced = useReducedMotion();
  return <section id="how-it-works" className="relative overflow-hidden bg-white px-5 py-24 md:px-10 md:py-36">
    <div className="pointer-events-none absolute left-1/2 top-0 h-[27rem] w-[75rem] -translate-x-1/2 rounded-full bg-[#e8f1ff] opacity-70 blur-3xl" />
    <div className="relative mx-auto max-w-[1100px]">
      <motion.div initial={{ opacity: 0, y: reduced ? 0 : 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ duration: .7, ease: [.16,1,.3,1] }} className="mx-auto max-w-[700px] text-center"><p className="text-[10px] font-bold uppercase tracking-[.2em] text-[#0b61d9]">How it works</p><TitleTag className="mt-4 text-balance text-[clamp(2.65rem,5.1vw,5rem)] font-medium leading-[.94] tracking-[-.065em] text-[#173b71]" style={{fontFamily:"var(--font-display)"}}>Three small moves.<span className="font-serif-accent block font-normal italic text-[#0b61d9]">One much louder signal.</span></TitleTag><p className="mx-auto mt-6 max-w-md text-[15px] leading-relaxed text-[#587091] md:text-[17px]">Bring in the praise, choose the stories that matter, and put them to work where trust needs a nudge.</p></motion.div>
      <div className="relative mt-16 grid gap-4 lg:grid-cols-3">
        {steps.map((step, index) => { const Icon = step.icon; const Visual = visuals[index]; return <motion.article key={step.number} initial={{opacity:0,y:reduced?0:25}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.2}} transition={{duration:.65,delay:index*.1,ease:[.16,1,.3,1]}} className={`group rounded-[28px] border p-5 shadow-[0_14px_32px_rgba(24,61,122,.07)] transition duration-300 hover:-translate-y-1 ${step.tone} md:p-6`}><div className="flex items-center justify-between"><span className={`flex h-9 w-9 items-center justify-center rounded-xl text-white ${step.accent}`}><Icon size={17}/></span><span className="text-[10px] font-bold tracking-[.14em] text-[#7890af]">{step.number}</span></div><div className="my-7 flex min-h-[210px] items-center rounded-[20px] border border-white/85 bg-white/75 p-4"><Visual/></div><p className="text-[10px] font-bold uppercase tracking-[.12em] text-[#0b61d9]">{step.subtitle}</p><h3 className="mt-2 text-[27px] font-semibold tracking-[-.045em] text-[#173b71]">{step.title}</h3><p className="mt-3 text-[13px] leading-relaxed text-[#5e7697]">{step.body}</p></motion.article>; })}
      </div>
    </div>
  </section>;
}
